server:
  port: 8081

odata:
  jpa:
    punit-name: Tutorial
    root-packages: pab.odata.olingo.entity
    mapping-path: /demo/service.svc

spring:
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/odata_jpa
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver